### ISSUE TITLE
Projecting points

### ISSUE THREAD

**Issue by Ceylo** [paulz/PerspectiveTransform#109]
Hello Paul,

This is more about understanding what is going wrong in my example than reporting a bug, as I have seen by running your example that it works perfectly fine.
I have pushed a simple test showing my issue at my fork: https://github.com/paulz/PerspectiveTransform/compare/master...Ceylo:master

I am stretching a quad horizontally, and I would expect that projecting each corner basically gives the output quad as a result (more or less some epsilon), but it is not the case. The test currently fails with:
<img width="445" alt="Capture d’écran 2020-08-14 à 19 10 08" src="https://user-images.githubusercontent.com/451334/90275041-f3b2d980-de61-11ea-9960-ced9f89e1562.png">

So it looks like all my points are shifted to the right by 3.333 and I really don't get why.

I am really not at ease with matrix transforms and especially I read in many places that after the matrix multiplication I should divide by w. But doing so just makes the result nonsense.

I would be really grateful if you have some insight about what's going on.
Thank you
Ceylo

**Comment by Ceylo** [comment]
It looks like the offset is always newWidth/oldWidth - newX-oldX

**Comment by paulz** [comment]
Have not yet had a chance to look into this yet. One idea is to see the expectations about Z axis. There are multiple 3D shapes that will make the same 2D projection. The perspective transform is taking advantage of that by normalizing Z axis twice: one time from source 2D to the 3D and second from destination. Thus even it produceS the 2D illusion, the resulting 3D is only one of many.

**Comment by paulz** [comment]
created a pull request with your changes to add inline comments, see https://github.com/paulz/PerspectiveTransform/pull/110
