### ISSUE TITLE
need help transforming UIImage

### ISSUE THREAD

**Issue by DeveloperTK** [paulz/PerspectiveTransform#12]
Hi, I am currently trying to do the following: 

I have an ARSCNView that detects an image. If that image is detected, the edge points are detected (that works, I have tried displaying the points). Now I want to put a snapshot of the current frame into an UIImageView and transform the image, so that I have a straight image of the detected one.

I need to do that, because the detected images are similar, but I want to identify a color at a specific position within that image.

Is there any way, I can do this with this library?

**Comment by paulz** [comment]
Please attach the screenshot here showing the view of the image with points. Or link to the project that I can run to create one. Thank you

**Comment by DeveloperTK** [comment]
Ok thank you for your quick resopnse. I ended up using CIPerspectiveCorrection, because using your library, i just transformed the image view but not the image.

But your library is great for other things, keep up the good work 👍

**Comment by paulz** [comment]
Good point, thank you. If you want to change the image you can apply the CoreImageFilters:
* [CIPerspectiveTransform](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CIPerspectiveTransform)
* [CIPerspectiveCorrection](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CIPerspectiveCorrection)

This PerspectiveTransform allows to change and overlay views, which allow more dynamic manipulation and takes less memory. And the end of the day you can also render view hierarchy into an image.
For that you can use [UIGraphicsGetImageFromCurrentImageContext()](https://developer.apple.com/documentation/uikit/1623924-uigraphicsgetimagefromcurrentima)
