### ISSUE TITLE
Straighten Perspective

### ISSUE THREAD

**Issue by yatharthchhabra** [paulz/PerspectiveTransform#140]
How are you able to straighten the perspective of the entire container image based on 4 corners?

**Comment by paulz** [comment]
good question, in general 3D transformations require more than 4 points, as you can see in CATransform3D.

Since we use affine transformations, we can apply https://en.wikipedia.org/wiki/Transformation_matrix#Perspective_projection

which allow us to assume w=1 plane of the destination image.
