### ISSUE TITLE
Is it possible to translate in z-axis after perspective transform is calculated?

### ISSUE THREAD

**Issue by eonist** [paulz/PerspectiveTransform#7]
The `layer.transform.m34` returns 0 which means there is no perspective? And thus its not possible to translate the transform in the z-axis?

I'm only able to translate in x and y axis at the moment. 

If you have a suggestion on where to look for a possible solution that would be great .

**Comment by paulz** [comment]
I am not following what you are trying to do, @eonist. 3D transform flattens to 2D screen at the end. If you need to simulate the Z-axis transformation you can just apply the affine scale transform to your view. This will create an effect of getting closer and further away from the user viewpoint. 

We are using infinite distance perspective, that's why changing `.m34` has no effect. This allows us to have a stable solution regardless of z-axis values.

**Comment by eonist** [comment]
Imagine you see a perspective square and want to project a square cube above it. Classic AR stuff. 

After a bit of research I don't think tis possible to move in the planes z axis. 

I tried your solution with a simple z-translation, but it doesn't work. As sort of excepted. 

```swift
let corners:[CGPoint] = [.init(x:100,y:130),.init(x:230,y:140),.init(x:200,y:220),.init(x:130,y:230)]
let arr = [corners[0],corners[1],corners[3],corners[2]]
let destination:Perspective = Perspective.init(.init(arr))
let start:Perspective = Perspective(.init(graphicView.frame))
let perspectiveTransformation = start.projectiveTransform(destination: destination)
let transform = CATransform3DMakeTranslation(0, 0, 100)
let newTransform = CATransform3DConcat(perspectiveTransformation,transform)
graphicView.layer.transform = newTransform
```

I guess you need to get `homography` and `perspectiveTransform` to achieve that and be sure the quad is a square in perspective. And not an elongated rectangle. 

I'm thinking I will try to just calculate the vanishing points from a perspective square and then translate along the z axis instead. Use geometry instead of matrix math.

**Comment by paulz** [comment]
Here is how translation along Z axis could be simulated:
![Simulator Screen Shot - iPhone 5s - 2019-03-13 at 16 38 52](https://user-images.githubusercontent.com/59230/54321463-85a01e00-45ae-11e9-8e1f-e326d12e0cd2.png)
![Simulator Screen Shot - iPhone 5s - 2019-03-13 at 16 36 48](https://user-images.githubusercontent.com/59230/54321464-85a01e00-45ae-11e9-8da9-a9d4b6db61bd.png)

I've modified the transform in the Example app.

**Comment by eonist** [comment]
Sorry might be lost in translation here. 

Here is the prototype code: https://github.com/eonist/PerspectiveTest

It can be opened in Xcode and simulated out of the box. 

What I am trying to achieve is to move in the planes z-axis. Not the camera z-axis. The orthogonal normal of the perspective plane so to speak. 

<img width="374" alt="Screenshot 2019-03-14 at 00 57 24" src="https://user-images.githubusercontent.com/11816788/54322293-ef431b00-45f4-11e9-978e-0f8f264352b3.png">

**Comment by paulz** [comment]
There is no such thing I can see as z-axis of the plane. To simulate translation you can just translate the container view:

![Simulator Screen Shot - iPhone XR - 2019-03-13 at 18 18 51](https://user-images.githubusercontent.com/59230/54324848-a40d1600-45bc-11e9-9e94-afe9a1479795.png)

**Comment by eonist** [comment]
Like here: you see the 2 other planes move correctly in the z-axis of the origin-plane, they follow the natural vanishing points of the perspective. Creating an illusion of a cube. 

<img width="490" alt="Screenshot 2019-03-14 at 13 16 59" src="https://user-images.githubusercontent.com/11816788/54356417-d91c7580-465b-11e9-8221-a56f2d45512b.png">

```swift
let rect:CGRect = {
   let size:CGSize = .init(width:200,height:200)
   let pos:CGPoint = {
      let screenCenter:CGPoint = .init(x:UIScreen.main.bounds.width/2,y:UIScreen.main.bounds.height/2)
      return .init(x:screenCenter.x - size.width/2, y:screenCenter.y - size.height/2)
   }()
   return .init(origin:pos,size:size)
}()
let graphicView:UIView = .init(frame:rect)
graphicView.backgroundColor = .blue

let graphicView2:UIView = .init(frame:rect)
graphicView2.backgroundColor = UIColor.red.withAlphaComponent(0.3)
view.addSubview(graphicView2)

let graphicView3:UIView = .init(frame:rect)
graphicView3.backgroundColor = UIColor.green.withAlphaComponent(0.3)
view.addSubview(graphicView3)

var transform:CATransform3D = CATransform3DIdentity
transform.m34 = 1.0 / -200
let yRotation:CGFloat = CGFloat(Double.pi / 6)
let xRotation:CGFloat = CGFloat(Double.pi / -5)
let zRotation:CGFloat = CGFloat(Double.pi / 8)
transform = CATransform3DRotate(transform,yRotation , xRotation, zRotation, 0.0)

let newTransform = CATransform3DTranslate(transform, 0, 0, -200)
let newNewTransform = CATransform3DTranslate(transform, 0, 0, -100)

graphicView.layer.transform = newTransform
graphicView2.layer.transform = newNewTransform
graphicView3.layer.transform = transform

view.addSubview(graphicView)
```

**Comment by eonist** [comment]
I would really like to do this with matrix math, but from my 1 day of research over at http://math.stackexchange.com it seems it is possible but very complicated. Coset clue I found was this: http://answers.opencv.org/question/5018/getperspectivetransform-mathematical-explanation/ 

In any case. I spent a few hours trying to solve this with trigonometry and I think I found a solution: 

<img width="490" alt="Screenshot 2019-03-14 at 20 21 09" src="https://user-images.githubusercontent.com/11816788/54386120-9036e200-4698-11e9-8f50-6b2ea4f59759.png">

It's basically about deriving the third vanishing point given a perspective square. From there we can find bounds of cube by using perspective ratios. Im only interested in generating a cube bound around the centre of the perspective square. But we could in general again use your solution and project images on the cube. It's not as fancy as apples AR-kit which use many points to derive correct perspective etc.

**Comment by paulz** [comment]
Hm, this looks like 3D modeling to me. Why not just take a view or several views and apply 3D transformations to build a cube? Then you can concatenate the set of transformation to add rotations, z-axis zoom, etc. This way you will have 2D projections from 3D "models".

The PerspectiveTransform is to simulate fitting between perspectives, basically reversing the modeling problem from 2D into 3D transformation.

Sure there are multiple ways to solve it without matrices, but they all end up ignoring z-axis and vanishing points, as those parameters are irrelevant for final 2D projection.

You can see that same 2D Quadrilateral could be a projection of many 3D objects, we are fixing them as an infinite viewpoint perspective to have parallel projection.

Here is an algebraic solution without matrices: https://github.com/paulz/PerspectiveTransform/blob/master/Example/Tests/QuadrilateralCalc.swift#L71
with the same result.

There is no point of using PerspectiveTransform to fit a view to the side of the cube, as you can just render any view on a side of a 3D cube, then render that cube in any perspective onto the 2D screen.

Probably I am missing something in a big picture of what you trying to build.

**Comment by paulz** [comment]
And love your use of Swift type inference, which I adopted in the last commits:
https://github.com/paulz/PerspectiveTransform/commit/2a1449fa5477a18fd973200f69fb7e1e6aefbd81

And here is how to build a cube using CATransform3D:
https://www.cocoanetics.com/2012/08/cubed-coreanimation-conundrum/

**Comment by eonist** [comment]
1. I came over the cocoanetics tutorial when I researched. Its great and I used to get my bearings with CATransform3d. But its not useful in the context of converting 2d- points to 3d-points. 

2. Swift interference is great. 

3. When it comes to taking many views to do 3d.modeling. The problem is I only have one. A perspective square. 

4. I built a solution using trigonometry that works: https://github.com/eonist/Cube 

I will try it in my simple AR app this weekend. Using an iPhone camera and a QR-code to represent the square. 

Thanks for your insight ^^

**Comment by paulz** [comment]
This is what I see so far on master: https://github.com/eonist/Cube/commit/db06a62da8d173ef8aafcef49f147de8e63218a8
![Simulator Screen Shot - iPhone XS - 2019-03-16 at 22 34 17](https://user-images.githubusercontent.com/59230/54485747-c496d380-483b-11e9-92a4-5a55387b8e99.png)

**Comment by paulz** [comment]
If you want to add z-axis values to the PerspectiveTransform, take a look at
https://github.com/paulz/PerspectiveTransform/blob/2ad52efe2206ceae8e67d4fe582d14cbbbd226ef/Pod/Classes/Matrix3x3%2B3D.swift#L33
Here we use 0 values for z-axis components and 1 for scale. This leaves you 8 extra degrees of freedom to construct resulting 3D transformation.

**Comment by eonist** [comment]
So that to3d method. What does it do? Can it produce results like in this image: 

![](https://user-images.githubusercontent.com/11816788/54356417-d91c7580-465b-11e9-8221-a56f2d45512b.png)

What I have discovered with the Cube module is that. It's sort of a fake 3d perspective. Although it's accurate it doesn't account for camera POV and distance to object. If I factor these things in as well I think it will work accurately. However. For what I need it for its good enough. As it gives a sense of depth in "AR space" I will make a .mp4 where I track an object via the camera, later tonight.

**Comment by eonist** [comment]
Tracking a QRCode with camera:  
<img width="320" alt="img" src="https://github.com/stylekit/img/blob/master/cube.gif?raw=true">

Needs some more refining.

**Comment by paulz** [comment]
@eonist do you mind if I close this since you found another solution using trigonometry?
